import libs = libzstd%lib{zstd}

if ($c.target.class != 'windows')
    c.libs += "-lpthread"

c.poptions += "-DBUILD2_ZSTD_VERSION=\"$version\"" "-I$src_base/programs"
exe{zstd}: programs/{h c}{* -zstdcli} programs/file{zstdcli.c} c{zstdcli} $libs
